### ISSUE TITLE
Just starting out. Failed to get mimic3 installed so Naomi can find it.

### ISSUE THREAD

**Issue by Eirikur** [NaomiProject/naomi-plugins#25]
I followed the directions to create a tts folder in ~/.config/naomi/plugs and clone the mimic3 repository into it. This did not result in Naomi being able to find the plugin. If I just need a pointer to the documentation on such discovery, I'll take it.

**Comment by aaronchantrill** [comment]
You should go to ~/.config/naomi/plugins/tts and then clone the directory.

You can also install it directly through Naomi. Just enter the command:
```
Naomi --install "mimic3-tts"
```
It should end up in the same location.

For a list of plugins available through the Naomi Plugin Exchange, just enter:
```
Naomi --list-available-plugins
```
Thanks for trying Naomi!

**Comment by aaronchantrill** [comment]
Sorry, just installed mimic3-tts through the interface and discovered a problem. The "python_required.txt" file should be named "python_requirements.txt". I'm updating now. After downloading, you also need to install the mycroft-mimic3-tts package by activating the "Naomi" virtual environment and then pip installing it. This is supposed to be done automatically when you install things through NPE.
```
naomi@renegade:~/Naomi$ workon Naomi
(Naomi) naomi@renegade:~/Naomi$ pip install mycroft-mimic3-tts[all]
```

**Comment by aaronchantrill** [comment]
@Eirikur I have updated the mimic3-tts repository with the fixes for the issues I discovered above. Please let me know if you are able to get Mimic 3 started.

**Comment by aaronchantrill** [comment]
I haven't heard back, so I'm closing this issue.
