### ISSUE TITLE
Add Category to plugins.csv

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/naomi-plugins#3]
I'd like to see a category column added to plugins.csv which would allow easy filtering into "speechhandler", "tts", "stt", "audioengine", "intentparser" etc.

**Comment by Longshotpro2** [comment]
Additions handled with [pull request #4](https://github.com/NaomiProject/naomi-plugins/pull/4). Any additional categories that are needed can be added.

**Comment by Longshotpro2** [comment]
Closing for now, reopen if there is an issue with the category column.
